### ISSUE TITLE
Envoy sidecar throwing deprecated warnings 

### ISSUE THREAD

**Issue by srispl** [istio/proxy#2234] opened 2019-05-24 18:44 UTC
Envoy sidecar logs are rolling with lot of warnings and the same log is repeating for 100s of times which is increasing log file size + complicate readability.

================= Consolidated log message ===================

[warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Cluster.hosts' from file cds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[warning][filter] [src/envoy/http/authn/http_filter_factory.cc:102] mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
[warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-05-06 22:04:02.520][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,

**Comment by howardjohn** [comment] 2019-05-29 14:42
In istio 1.2 we added a flag to pilot agent, proxyComponentLogLevel. This allows you to configure log levels by component. We default this to misc:error which hides the deprecated messages.

**Comment by esnible** [comment] 2019-06-12 20:50
Closing as a duplicate of https://github.com/istio/proxy/issues/2159

**Closed by esnible** 2019-06-12 20:50 UTC
