### ISSUE TITLE
mixer filter aborts due to a call to pure_virtual ()

### ISSUE THREAD

**Issue by mandarjog** [istio/proxy#279] opened 2017-04-30 23:40 UTC
When proxy is put under load this seems to happen.
How to recreate:
Install bookinfo.

```
wrk -t500 -c2500 -d5m --latency -s ~/get.lua $GATEWAY_URL/productpage   
cat ~/get.lua
mjog@mjog0:~/GOHOME/src/istio.io/istio$ cat ~/get.lua 
wrk.method = "GET"
wrk.headers["Cookie"] = "user=jason; foo=bar"
wrk.headers["Content-Type"] = "application/json"
```

```
0  0x00007f82a9dc8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f82a9dca02a in __GI_abort () at abort.c:89
#2  0x00007f82aa70a84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f82aa7086b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f82aa708701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f82aa70923f in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000044011e in Http::Mixer::Instance::completeCheck (this=0x2219840, status=...) at src/envoy/mixer/http_filter.cc:273
#7  0x000000000043fa28 in Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const (__closure=0x27d2c58, status=...) at src/envoy/mixer/http_filter.cc:216
#8  0x0000000000442074 in std::_Function_handler<void (google::protobuf::util::Status const&), Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}>::_M_invoke(std::_Any_data const&, google::protobuf::util::Status const&) (__functor=..., 
    __args#0=...) at /usr/include/c++/5/functional:1871
#9  0x0000000000429695 in std::function<void (google::protobuf::util::Status const&)>::operator()(google::protobuf::util::Status const&) const (
    this=0x27d2c58, __args#0=...) at /usr/include/c++/5/functional:2267
#10 0x000000000043f82b in Http::Mixer::Instance::wrapper(std::function<void (google::protobuf::util::Status const&)>)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const::{lambda()#1}::operator()() const (__closure=0x27d2c30)
    at src/envoy/mixer/http_filter.cc:185
#11 0x0000000000441a7b in std::_Function_handler<void (), Http::Mixer::Instance::wrapper(std::function<void (google::protobuf::util::Status const&)>)::{lambda(google::protobuf::util::Status const&)#1}::operator()(google::protobuf::util::Status const&) const::{lambda()#1}>::_M_invoke(std::_Any_data const&)
    (__functor=...) at /usr/include/c++/5/functional:1871
#12 0x0000000000464cc0 in std::function<void ()>::operator()() const (this=0x7f82a8b2ea20) at /usr/include/c++/5/functional:2267
#13 0x000000000060442c in Event::DispatcherImpl::runPostCallbacks (this=0x17f0bb0) at external/envoy/source/common/event/dispatcher_impl.cc:152
#14 0x00000000006037f3 in Event::DispatcherImpl::<lambda()>::operator()(void) const (__closure=0x17f0ad8)
    at external/envoy/source/common/event/dispatcher_impl.cc:28
```

**Comment by qiwzhang** [comment] 2017-05-02 18:18
I believe it is fixed now

**Closed by qiwzhang** 2017-05-02 18:18 UTC

**Comment by kyessenov** [comment] 2017-05-02 18:51
Was the issue caused by Mixer not responding fast enough? We need a way to reproduce the error and a regression test.
