### ISSUE TITLE
Add TCP Filter

### ISSUE THREAD

**Issue by jasminejaksic** [istio/proxy#167] opened 2017-03-14 01:35 UTC
Add TCP filters to call Mixer check, report and Quota

**Comment by kyessenov** [comment] 2017-03-15 23:18
duplicate of #44. Is this really for alpha?

**Closed by kyessenov** 2017-03-15 23:18 UTC

**Comment by jasminejaksic** [comment] 2017-03-16 19:58
That was my understanding based on the feature prioritization we did a few weeks ago. But I agree it's not needed for MVP, more of a nice-to-have for Alpha.
