### ISSUE TITLE
missing symbols in stack traces

### ISSUE THREAD

**Issue by ldemailly** [istio/proxy#370] opened 2017-06-14 16:53 UTC
there must be something wrong with our build that we require addr2line/a script to translate stack traces

example: https://github.com/istio/pilot/issues/869

**Comment by qiwzhang** [comment] 2017-06-14 17:05
This is required from Envoy issue.  Please file this at Envoy

**Comment by ldemailly** [comment] 2017-06-14 22:06
we build from source, I want to take ownership of the setup we distribute

**Comment by lizan** [comment] 2017-06-14 22:16
@ldemailly See https://github.com/lyft/envoy/pull/833 for the reason they have script to decode the stack trace, and it might apply to us too.

**Comment by sebastienvas** [comment] 2017-06-15 01:35
I unassigned myself.

**Comment by qiwzhang** [comment] 2017-06-16 19:16
There is nothing wrong with our build.   To get back trace is an extra feature Envoy added.  Otherwise, you will just get one line in the log "Core Dumpped".

The issue is:  If a binary segment fails,   you only see one line "Core dumped with segment fail".   Not back trace.   Envoy adds a signal_handler to get back_trace and dump to the log.  But in order to not link in many other dependencies,  they decided to dump the addresses, and use script to convert the addresses to symbols. 

I will close this issue

**Closed** 2017-06-16 19:17 UTC
